version: '2'

services:
  app:
    image: 'simplewebapp:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db
      - activemq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/employeedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#      - SPRING_ACTIVEMQ_IN-MEMORY=true
#      - SPRING_ACTIVEMQ_POOL_ENABLED=false
#      - SPRING_ACTIVEMQ_PACKAGES_TRUST-ALL=false
      - SPRING_ACTIVEMQ_BROKER-URL=tcp://localhost:61616
      - SPRING_ACTIVEMQ_USER=admin
      - SPRING_ACTIVEMQ_PASSWORD=admin
#      - SPRING_ACTIVEMQ_PACKAGES_TRUSTED=*

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=employeedb

  activemq:
    image: webcenter/activemq:5.14.3
    container_name: activemq
    environment:
      ACTIVEMQ_ADMIN_LOGIN: "admin"
      ACTIVEMQ_CONFIG_QUEUES: simplewebapp.queue.delete;simplewebapp.queue.save

    ports:
      - "8161:8161"
      - "61616:61616"
      - "61613:61613"